# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- source

pool: 
  vmImage: windows-latest

variables:
  system.debug: true

steps:
- checkout: self
  persistCredentials: true
- task: NodeTool@0
  inputs:
    versionSpec: '18.15.0'
  displayName: 'Install Node.js'
  
# - script: |
#     npm install -g npm@latest
#     npm install
#     npm run build
#     cd dist
#   displayName: 'npm install and build'

- task: CmdLine@2
  inputs:
    script: |
      echo "--------------- Npm Install ---------------"
      npm install
  displayName: 'Installing Dependencies'

- task: CmdLine@2
  inputs:
    script: |
      echo "--------------- Npm Build ---------------"
      npm run build
  displayName: 'Build and Deploy Changes'

- task: CmdLine@2
  inputs:
    script: |
      echo "--------------- Set Git Config ---------------"
      git config --global user.email "shubham.sharma.17@outlook.com"
      git config --global user.name "Shubham Sharma"
  displayName: 'Set Git Config'
  
- task: CmdLine@2
  inputs:
    script: |
      echo "--------------- Add Origin ---------------"
      ls
      cd dist
      ls
      git remote -v
      git remote rm origin
      git remote -v
      git remote add origin https://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@github.com/shubhamsharma11/shubhamsharma11.github.io.git
      git remote -v
      echo "--------------- Git Initialize ---------------"
      git init
      echo "--------------- Set Branch ---------------"
      git branch -M main
      echo "--------------- Stage Changes ---------------"
      git add -A
      echo "--------------- Commit Changes ---------------"
      git commit -m "deploy"
      echo "--------------- Push Changes ---------------"
      git push -f -u origin main
  displayName: 'Commit and Push Changes'