# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- source

pool: myPool

steps:
- checkout: self
  persistCredentials: true
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    git config user.email "yourmail" 
    git config user.name "yourname"
    npm install
    npm run build
    npm run deploy -- -r https://$(github_pat)@github.com/shubhamsharma11/shubhamsharma11.github.io.git
  displayName: 'npm install and build'