# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- source

pool: 
  vmImage: ubuntu-latest

variables:
  system.debug: true

steps:
- checkout: self
  persistCredentials: true
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'
  
- script: |
    npm install
    npm run build
    cd dist
    git config --global user.email "shubham.sharma.17@outlook.com"
    git config --global user.name "Shubham Sharma"
    echo "---------------"
    git remote -v
    git remote rm origin
    git remote -v
    git remote add origin https://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@github.com/shubhamsharma11/shubhamsharma11.github.io.git
    git remote -v
    echo "---------------"
    git init
    git branch -M main
    git add -A
    echo "commit"
    git commit -m "deploy"
    echo "push"
    git push -f -u origin main
  displayName: 'npm install and build'