name: Deploy to Github Pages
on:
    push:
        branches:
            - master

jobs:
    deploy:
        name: Deploy Application
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@master							
            - name: Create Node Environment
              uses: actions/setup-node@v1
              with: 
                node-version: 10.x
            - name: Install Packages and Build Application
              run: |
                npm install
                npm run build
            - name: Deploy
              uses: s0/git-publish-subdir-action@develop
              env:
                REPO: https://github.com/shubhamsharma11/shubhamsharma11.github.io.git
                BRANCH: main
                FOLDER: dist
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
