name: Deploy to Github Pages
on:
    push:
        branches:
            - master

jobs:
    deploy:
        name: Deploy Application
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@master							
            - name: Create Node Environment
              uses: actions/setup-node@v1
              with: 
                node-version: 18.x
            - name: Install Packages and Build Application
              run: |
                npm install
                npm run build
            - name: Deploy
              uses: s0/git-publish-subdir-action@develop
              env:
                REPO: git@github.com:shubhamsharma11/shubhamsharma11.github.io.git
                BRANCH: main
                FOLDER: dist
                SSH_PRIVATE_KEY: ${{ secrets.NEW_PRIVATE_KEY }}
                # KNOWN_HOSTS_FILE: resources/known_hosts
                # Deploy to another repo - name: Deploy uses: s0/git-publish-subdir-action@develop env: REPO: git@github.com:owner/repo.git BRANCH: gh-pages FOLDER: build SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }} KNOWN_HOSTS_FILE: resources/known_hosts # Needed if target repo is not on github.com
